name: assert count_ones(2147483647) == 31
limit: 5000
memory_size: 0x1000
memory_mapped_io:
  0x80: [2147483647]
  0x84: []

reports:
  - name: Step-by-step
    slice: all
    view: |
      {pc}:	{instruction} {pc:label} -> {memory:0:16}

  - name: Check results
    slice: last
    filter:
      - state
    view: |
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [31]